---
output:
  word_document: default
  html_document: default
---
## Composição das Despesas do mês

```{r grafico, echo=FALSE, fig.align='center', fig.width=6, fig.height=6}
print(grafico)
```

## Discriminação das Despesas

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> conta </th>
   <th style="text-align:left;"> data </th>
   <th style="text-align:left;"> descricao </th>
   <th style="text-align:left;"> categoria </th>
   <th style="text-align:left;"> centro </th>
   <th style="text-align:left;"> IRPF </th>
   <th style="text-align:left;"> etiqueta </th>
   <th style="text-align:right;"> valor </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Compra com Cartão - 02/01 09:52 AGROSADY </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 57.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Compra com Cartão - 02/01 10:01 ZHU YANGJI </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 45.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pix - Enviado - 02/01 12:46 Gm Comercio Varejista De G </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 122.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pix - Enviado - 02/01 13:07 Evanderson Lima </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pix - Enviado - 02/01 14:21 Bela Beleza Cosmeticos </td>
   <td style="text-align:left;"> Cosméticos </td>
   <td style="text-align:left;"> Cuidados pessoais </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 33.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pagamento de Boleto - COIMEX ADMINISTRADORA DE CONSO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 930.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pagamento de Boleto - PJBANK PAGAMENTOS S.A. </td>
   <td style="text-align:left;"> Escola Amélie </td>
   <td style="text-align:left;"> Educação </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 330.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pagamento de Boleto - PJBANK </td>
   <td style="text-align:left;"> Escola Amélie </td>
   <td style="text-align:left;"> Educação </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 480.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pix - Enviado - 02/01 21:54 Igor Mendonca Cardoso Gome </td>
   <td style="text-align:left;"> Transferências entre Contas </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 309.46 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Pix - Enviado - 02/01 22:04 Departamento Estadual De T </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 135.62 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Cobrança de I.O.F. </td>
   <td style="text-align:left;"> IOF </td>
   <td style="text-align:left;"> Despesas financeiras </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 11.45 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-03 </td>
   <td style="text-align:left;"> Pix - Enviado - 03/01 14:41 Nova Escola </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 1016.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-03 </td>
   <td style="text-align:left;"> Pagamento de Boleto - ORDEM DOS ADVOGADOS DO BRASIL </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 792.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-03 </td>
   <td style="text-align:left;"> Pagamento ASSEFAZ - ASSEFAZ PLANOS DE SAUDE </td>
   <td style="text-align:left;"> Plano de Saúde </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 4349.48 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-04 </td>
   <td style="text-align:left;"> Pix - Enviado - 04/01 16:15 Marilene Silva Souza </td>
   <td style="text-align:left;"> Empregada </td>
   <td style="text-align:left;"> Serviços domésticos </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 1469.28 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-04 </td>
   <td style="text-align:left;"> Pix - Enviado - 04/01 20:47 Milton Fernandes Borges </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 40.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Compra com Cartão - 05/01 21:29 PAG*VandaBarreto </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 30.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Pagamento de Boleto - CEA PAY - ORION INST. DE PAGAMENTO S A </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 36.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Pagto cartão crédito - ELO NANQUIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 36.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Tarifa Pacote de Serviços - Cobrança referente 05/01/2023 </td>
   <td style="text-align:left;"> Tarifas Bancárias </td>
   <td style="text-align:left;"> Despesas financeiras </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 79.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Pagamento de Telefone - CLARO BA /SE/ MG </td>
   <td style="text-align:left;"> Telefone </td>
   <td style="text-align:left;"> Comunicação </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 130.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Brasilprev - BRASILPREV SEGUROS </td>
   <td style="text-align:left;"> Seguros </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 139.64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Brasilprev - BRASILPREV SEGUROS </td>
   <td style="text-align:left;"> Seguros </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 150.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Cobrança de Juros </td>
   <td style="text-align:left;"> Juros </td>
   <td style="text-align:left;"> Despesas financeiras </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 11.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-06 </td>
   <td style="text-align:left;"> Pagamento de Boleto - SOCIEDADE MINEIRA DE CULTURA </td>
   <td style="text-align:left;"> Doutorado Fernanda </td>
   <td style="text-align:left;"> Educação </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 595.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-06 </td>
   <td style="text-align:left;"> Pagamento de Boleto - NU PAGAMENTOS SA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 449.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-06 </td>
   <td style="text-align:left;"> Pix - Enviado - 06/01 15:39 Rozemeire Novais Santos </td>
   <td style="text-align:left;"> Faxina </td>
   <td style="text-align:left;"> Serviços domésticos </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 120.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-06 </td>
   <td style="text-align:left;"> Pix - Enviado - 06/01 20:05 Matheus Peixoto Amaral </td>
   <td style="text-align:left;"> Pagamento de Empréstimos </td>
   <td style="text-align:left;"> Amortizações </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-06 </td>
   <td style="text-align:left;"> Pagto Energia Elétrica - COELBA - DÉBITO ENERGIA </td>
   <td style="text-align:left;"> Energia Elétrica </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 170.89 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Compra com Cartão - 07/01 11:46 PADARIA CONQUISTA </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 3.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Compra com Cartão - 07/01 18:35 ACARAJE OFICIAL </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 32.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Compra com Cartão - 09/01 15:00 BANCA CONQUISTA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 17.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Compra com Cartão - 09/01 15:04 DELICIAS DO MILHO 2 </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 8.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Pix - Enviado - 07/01 08:57 Cristiane Seroa Da Silva </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 122.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-09 </td>
   <td style="text-align:left;"> Pix - Enviado - 07/01 18:39 Pedrita Souza Caires </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-11 </td>
   <td style="text-align:left;"> Transferência enviada - 11/01 17:18 ERNESTO S RIBEIRO NETO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 260.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-11 </td>
   <td style="text-align:left;"> Pix - Enviado - 11/01 13:22 Igor Mendonca Cardoso Gome </td>
   <td style="text-align:left;"> Transferências entre Contas </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 2274.24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-11 </td>
   <td style="text-align:left;"> Pix - Enviado - 11/01 17:18 Janaina De Matos Sarrizo D </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 4.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-11 </td>
   <td style="text-align:left;"> Pix - Enviado - 11/01 17:27 Gabriela De Quadros Carval </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 168.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-12 </td>
   <td style="text-align:left;"> Compra com Cartão - 12/01 13:33 MERCADOPAGO*PERICLES </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 22.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-12 </td>
   <td style="text-align:left;"> Pix - Enviado - 12/01 14:45 Joao Guilherme Carvalho Go </td>
   <td style="text-align:left;"> Mesada Guilherme </td>
   <td style="text-align:left;"> Despesas de Guilherme </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 300.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-13 </td>
   <td style="text-align:left;"> Compra com Cartão - 13/01 11:32 MERCADOPAGO*CANDIDO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 203.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-13 </td>
   <td style="text-align:left;"> Pix - Enviado - 13/01 07:37 Antonio Balbino Couto </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 1400.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-13 </td>
   <td style="text-align:left;"> Pix - Enviado - 13/01 09:08 Antonio Balbino Couto </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-16 </td>
   <td style="text-align:left;"> Pagamento de Boleto - PORTOSEG SA C FINANC E INVEST </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 1335.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-16 </td>
   <td style="text-align:left;"> Pix - Enviado - 14/01 10:10 Zeilton Moreira Dos Santos </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 40.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-16 </td>
   <td style="text-align:left;"> Pagamento de Telefone - VIVO FIXO NACIONAL 13 DIG </td>
   <td style="text-align:left;"> IOF </td>
   <td style="text-align:left;"> Despesas financeiras </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 91.43 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-17 </td>
   <td style="text-align:left;"> Pix - Enviado - 17/01 18:14 Arena Beach Sunset Clube E </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-18 </td>
   <td style="text-align:left;"> Compra com Cartão - 18/01 21:26 SUPERMERCADO SANT </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 10.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-18 </td>
   <td style="text-align:left;"> Pix - Enviado - 18/01 10:33 Launch Pad Tecnologia, Ser </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 29.94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-18 </td>
   <td style="text-align:left;"> Pix - Enviado - 18/01 17:55 Jose Maria Alves Caires </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 5.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-19 </td>
   <td style="text-align:left;"> Compra com Cartão - 19/01 12:56 CONFEITARIA VIDAL </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 33.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-19 </td>
   <td style="text-align:left;"> Compra com Cartão - 19/01 13:14 SUPERMERCADO SANT </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 157.04 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-19 </td>
   <td style="text-align:left;"> Pix - Enviado - 19/01 10:35 R A R Da Silva </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 46.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Compra com Cartão - 20/01 08:47 DROGASIL 1706 </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 161.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Compra com Cartão - 20/01 15:46 BELA BELEZA COSME </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 36.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Compra com Cartão - 20/01 15:54 BAZAR ALFA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 11.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Compra com Cartão - 20/01 18:26 VISORE </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 60.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Compra com Cartão - 20/01 19:02 PADARIA MAXIMA </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Pix - Enviado - 20/01 09:34 Vinicius Lemos Da Silva Re </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 2000.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Pix - Enviado - 20/01 11:35 Arã De Oliveira Costa </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 35.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-20 </td>
   <td style="text-align:left;"> Pix - Enviado - 20/01 16:05 Serbet </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 8.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 21/01 11:43 SUPERMERCADO SANT </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 83.51 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 22/01 17:38 GBARBOSA - LOJA - </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 54.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 23/01 12:20 COM TUDO MADEIREIRA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 725.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 21/01 13:50 ARENA BEACH SUNSE </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 40.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 23/01 12:29 POSTO VITORIA </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 21/01 18:39 MERCADOPAGO*BBURGUER </td>
   <td style="text-align:left;"> Restaurantes e Lanches </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 75.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Compra com Cartão - 23/01 19:10 MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 353.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 21/01 10:35 Luizete De Souza Alves </td>
   <td style="text-align:left;"> Feira </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 52.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 21/01 10:51 Suely Moura Cairo </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 6.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 21/01 10:56 Tamyris Prado Galvao </td>
   <td style="text-align:left;"> Feira </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 35.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 21/01 15:32 Arena Beach Sunset Clube E </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 10.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 22/01 16:58 Raia Drogasil </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 37.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 23/01 09:51 Empreend Pague Menos Sa </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 52.85 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pix - Enviado - 23/01 15:15 Maria Eleusa Couto Coutinh </td>
   <td style="text-align:left;"> Música Amélie </td>
   <td style="text-align:left;"> Educação </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 132.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-23 </td>
   <td style="text-align:left;"> Pagamento Fatura de Água - EMBASA </td>
   <td style="text-align:left;"> Água </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 117.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-24 </td>
   <td style="text-align:left;"> Compra com Cartão - 24/01 17:06 CHAME CHAME01 </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 21.45 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-24 </td>
   <td style="text-align:left;"> Pix - Enviado - 24/01 10:23 Luma Estacionamento </td>
   <td style="text-align:left;"> Estacionamento </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 8.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-24 </td>
   <td style="text-align:left;"> Pix - Enviado - 24/01 13:53 Maria Madalena Rodrigues D </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 11.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-25 </td>
   <td style="text-align:left;"> Compra com Cartão - 25/01 17:59 PAGUE MENOS 1211 </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 10.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-25 </td>
   <td style="text-align:left;"> Compra com Cartão - 25/01 18:31 SUPERMERCADO SANT </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 26.24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-26 </td>
   <td style="text-align:left;"> Compra com Cartão - 26/01 10:49 NEY SOM </td>
   <td style="text-align:left;"> Instrumentos Musicais </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 32.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-26 </td>
   <td style="text-align:left;"> Pix - Enviado - 26/01 10:50 William Santos De Sousa </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 64.45 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-26 </td>
   <td style="text-align:left;"> Pix - Enviado - 26/01 16:49 Jose Maria Alves Caires </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 5.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-27 </td>
   <td style="text-align:left;"> Pix - Enviado - 27/01 07:42 Matheus Peixoto Amaral </td>
   <td style="text-align:left;"> Pagamento de Empréstimos </td>
   <td style="text-align:left;"> Amortizações </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 168.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-27 </td>
   <td style="text-align:left;"> Pix - Enviado - 27/01 11:38 Marcelo Junho Chiarini </td>
   <td style="text-align:left;"> Dentistas </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 300.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-30 </td>
   <td style="text-align:left;"> Transferência enviada - 29/01 15:33 RAIMUNDO C CARVALHO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 200.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-31 </td>
   <td style="text-align:left;"> Pix - Enviado - 31/01 18:13 Maria Madalena Rodrigues D </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BB </td>
   <td style="text-align:left;"> 2023-01-31 </td>
   <td style="text-align:left;"> Pix - Enviado - 31/01 22:50 Joao Guilherme Carvalho Go </td>
   <td style="text-align:left;"> Mesada Guilherme </td>
   <td style="text-align:left;"> Despesas de Guilherme </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 300.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bradesco </td>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:left;"> Reg Lancamento </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 634.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bradesco </td>
   <td style="text-align:left;"> 2023-01-04 </td>
   <td style="text-align:left;"> Pix Qrcode Est </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 1296.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bradesco </td>
   <td style="text-align:left;"> 2023-01-05 </td>
   <td style="text-align:left;"> Prest Fin Imob </td>
   <td style="text-align:left;"> Prestação Casa </td>
   <td style="text-align:left;"> Amortizações </td>
   <td style="text-align:left;"> SIM </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 2572.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Bradesco </td>
   <td style="text-align:left;"> 2023-01-31 </td>
   <td style="text-align:left;"> Pix Qrcode Din </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 208.65 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-09-23 </td>
   <td style="text-align:left;"> Amazon com br 3/7 </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-20 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 43.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-20 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 46.61 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-23 </td>
   <td style="text-align:left;"> MP SHELLBOX </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 176.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-23 </td>
   <td style="text-align:left;"> POSTO ELITE </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 24.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-24 </td>
   <td style="text-align:left;"> NOVA ERA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-24 </td>
   <td style="text-align:left;"> RMIX COMERCIO DE GENRE </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 510.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> POLO WEAR SHOPPING DA 1/3 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 99.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 125.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> DECATHLON SALVADOR </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 89.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> TFCO BAHIA CAFE LTDA M </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-26 </td>
   <td style="text-align:left;"> TRMF CONSULT SunoMembr 1/12 </td>
   <td style="text-align:left;"> Assinaturas </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 99.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-26 </td>
   <td style="text-align:left;"> MP SHELLBOX </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 76.49 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-26 </td>
   <td style="text-align:left;"> CONFRARIA DO FRANCA </td>
   <td style="text-align:left;"> Restaurantes </td>
   <td style="text-align:left;"> Alimentação fora de casa </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 300.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-27 </td>
   <td style="text-align:left;"> POSTO AMARAL </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 175.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-28 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 4.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-28 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 853.67 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-28 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 52.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-28 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 3.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-29 </td>
   <td style="text-align:left;"> Panificadora </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 7.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-29 </td>
   <td style="text-align:left;"> FernandaDeJesus </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 5.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-29 </td>
   <td style="text-align:left;"> SUPERMERCADO SAO GERAL </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 16.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-30 </td>
   <td style="text-align:left;"> Uber    UBER    TRIP </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-30 </td>
   <td style="text-align:left;"> DocaCozinha </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 6.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-30 </td>
   <td style="text-align:left;"> DocaCozinha </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 2.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-30 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-02 </td>
   <td style="text-align:left;"> ESTAC MEDICAL PARK </td>
   <td style="text-align:left;"> Estacionamento </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 7.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-03 </td>
   <td style="text-align:left;"> INDIGO </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 7.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-03 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 64.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> MERCADOLIVRE NEREIDESA </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 160.74 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 115.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 39.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 61.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> Read S  GOL DKWMZR 1/4 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 252.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> HOTELDO 1/4 </td>
   <td style="text-align:left;"> Hospedagem </td>
   <td style="text-align:left;"> Viagens e Lazer </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 773.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> LATAM AIRLIN ZONEBX015 1/4 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 104.64 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> Read S  LAN ZONEBX </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 40.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-10 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 121.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-13 </td>
   <td style="text-align:left;"> SPOTIFY </td>
   <td style="text-align:left;"> Assinaturas </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 34.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> HAVAN VOTORIA DA CONQU </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 107.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> MP SHELLBOX </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.74 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 4.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> MIX MATEUS </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 39.73 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> COOP DE CONS DE TRAN </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 103.60 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-16 </td>
   <td style="text-align:left;"> MP SHELLBOX </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 165.37 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-17 </td>
   <td style="text-align:left;"> Amazon com br </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 33.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-17 </td>
   <td style="text-align:left;"> MERCADO DA PRAIA </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 10.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-19 </td>
   <td style="text-align:left;"> BOMPRECO VASCO DA GAMA </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 104.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-20 </td>
   <td style="text-align:left;"> LuisCarlosViana </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 10.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> MP SHELLBOX </td>
   <td style="text-align:left;"> Combustível </td>
   <td style="text-align:left;"> Carro </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 189.77 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> SYMPLA  HIPER MEIOS CO </td>
   <td style="text-align:left;"> Eventos </td>
   <td style="text-align:left;"> Viagens e Lazer </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 60.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> MEU CHAPA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> REDEMIX </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 70.47 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> SPBA SHP DA BAHIA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> R S S  COMERCIAL DE AL </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 70.95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> HIPERIDEAL </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 37.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> SALGADEIRA DO QUARESMA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 32.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> TOCA DO COBRA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 225.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> SPBAPITUBA </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 61.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-23 </td>
   <td style="text-align:left;"> SEGURO SUPERPROTEGIDO </td>
   <td style="text-align:left;"> Seguros </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> RMIX COMERCIO DE GENRE </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 169.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> MORENA </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 239.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> COMERCIAL DE OCMBUSTIV </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 110.61 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> SAGRES </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-23 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-24 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 24.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> 99APP        99App </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 22.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> POLO WEAR SHOPPING DA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 219.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-27 </td>
   <td style="text-align:left;"> DROGARIA SAO PAULO SA </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-27 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.85 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-28 </td>
   <td style="text-align:left;"> Rrkcomldealim </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 6.88 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-29 </td>
   <td style="text-align:left;"> POLO WEAR SHOPPING DA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 188.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-30 </td>
   <td style="text-align:left;"> 99APP        99App </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-03 </td>
   <td style="text-align:left;"> DROGASIL </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-03 </td>
   <td style="text-align:left;"> Rrkcomldealim </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 12.76 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 18.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-12 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 8.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-13 </td>
   <td style="text-align:left;"> 99APP        99App </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 20.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-13 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 22.37 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> Rrkcomldealim </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 24.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> ZILMEIRY DOS SANTOS S </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> DY MIX MINIMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 26.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-16 </td>
   <td style="text-align:left;"> 99APP        99App </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 20.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-16 </td>
   <td style="text-align:left;"> Barbearia Irmandade </td>
   <td style="text-align:left;"> Barbeiro </td>
   <td style="text-align:left;"> Cuidados pessoais </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 25.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-16 </td>
   <td style="text-align:left;"> CANTINA DO VALE </td>
   <td style="text-align:left;"> Restaurantes </td>
   <td style="text-align:left;"> Alimentação fora de casa </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-17 </td>
   <td style="text-align:left;"> HIPERIDEAL </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 39.45 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-18 </td>
   <td style="text-align:left;"> G BARBOSA LOJA   274 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 51.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-20 </td>
   <td style="text-align:left;"> ZMC COM DE PROD PANIFI </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-20 </td>
   <td style="text-align:left;"> YAN PING SDB </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 66.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> 2791 DROGASIL </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 92.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> PASTA E BRASA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 39.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> SPBA SHP DA BAHIA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 29.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> FILIAL BAHIA SHOPPING </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 34.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-21 </td>
   <td style="text-align:left;"> POLO WEAR SHOPPING DA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 79.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> G MIX SUPERMERCADO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 35.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-08-14 </td>
   <td style="text-align:left;"> Produtos Globo 5/12 </td>
   <td style="text-align:left;"> Assinaturas </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 42.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-10-03 </td>
   <td style="text-align:left;"> MACELA DOURADA MANIPU 3/3 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 226.66 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-14 </td>
   <td style="text-align:left;"> SINGULAR PHARMA 2/2 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 290.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-16 </td>
   <td style="text-align:left;"> Mercadoticamt18 2/2 </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 104.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-18 </td>
   <td style="text-align:left;"> BellaNude 2/3 </td>
   <td style="text-align:left;"> Tratamentos Fernanda </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 169.66 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-19 </td>
   <td style="text-align:left;"> CALDEIRA SPORTS CONQUI 2/3 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 317.85 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-24 </td>
   <td style="text-align:left;"> JUVAN S </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 97.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> ML PREPARO DE ALIMENTO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 5.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> ML PREPARO DE ALIMENTO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 33.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> ALO BEBE 0229 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> HAV SALVADOR SHOP </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 38.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-25 </td>
   <td style="text-align:left;"> TRACK FIELD </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 89.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-11-29 </td>
   <td style="text-align:left;"> NubiaCoelhoErthal </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 50.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-01 </td>
   <td style="text-align:left;"> ZP           SYMPLA 1/5 </td>
   <td style="text-align:left;"> Eventos </td>
   <td style="text-align:left;"> Viagens e Lazer </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 53.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-01 </td>
   <td style="text-align:left;"> VISORE 1/2 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 197.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-01 </td>
   <td style="text-align:left;"> CAMILA OLIVEIRA MENEG 1/2 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 112.85 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-01 </td>
   <td style="text-align:left;"> DROGASIL 2304 </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 62.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-02 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 7.41 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-02 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 12.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-02 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 29.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 31.94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> GBARBOSA   LOJA   G112 </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 91.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> COCINA MEXICANA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 175.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 12.95 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-04 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 29.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> CONFEITARIA VIDAL </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 23.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> FILIAL </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 28.24 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> BY DERME COSMETICOS D </td>
   <td style="text-align:left;"> Cosméticos </td>
   <td style="text-align:left;"> Cuidados pessoais </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 52.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-05 </td>
   <td style="text-align:left;"> VENDA TOPFOOD CONQUIST </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 49.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> DROGASIL 2304 </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 57.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> PADARIA MAXIMA </td>
   <td style="text-align:left;"> Padaria </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 6.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-06 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 34.28 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-07 </td>
   <td style="text-align:left;"> INTEGRAR SERVICO INTEGRAD </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 120.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-07 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 119.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-07 </td>
   <td style="text-align:left;"> VISORE </td>
   <td style="text-align:left;"> NA </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 40.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-07 </td>
   <td style="text-align:left;"> DEPYL ACTION </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 44.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-07 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 5.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-08 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 95.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-08 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.79 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-08 </td>
   <td style="text-align:left;"> SUPERMERCADO SANTO </td>
   <td style="text-align:left;"> Supermercado </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 132.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 159.62 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 159.62 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-09 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 159.62 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-10 </td>
   <td style="text-align:left;"> SUMUP  MEINHOCAS </td>
   <td style="text-align:left;"> Roupas </td>
   <td style="text-align:left;"> Vestuário, cama, mesa e banho </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-10 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 20.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-11 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 28.09 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-12 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-13 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 95.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 4.70 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-14 </td>
   <td style="text-align:left;"> NETFLIX COM </td>
   <td style="text-align:left;"> Assinaturas </td>
   <td style="text-align:left;"> Despesas domésticas regulares (exceto serviços de doméstica) </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 55.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> ALMA SHOP Alma 1/3 </td>
   <td style="text-align:left;"> Roupas </td>
   <td style="text-align:left;"> Vestuário, cama, mesa e banho </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 209.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-15 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 56.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-16 </td>
   <td style="text-align:left;"> LOJAS AMERICANAS 5116 </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 116.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-17 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 8.60 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-17 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 14.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> AME DIGITAL AME Digita </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 191.87 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-22 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-23 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.94 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-23 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 13.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-23 </td>
   <td style="text-align:left;"> Uber UBER  TRIP HELP UBER </td>
   <td style="text-align:left;"> Táxi/Uber </td>
   <td style="text-align:left;"> Transporte </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-23 </td>
   <td style="text-align:left;"> AME DIGITAL AME Digita </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 19.80 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> DROGARIA ONLINE </td>
   <td style="text-align:left;"> Remédios </td>
   <td style="text-align:left;"> Saúde </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 38.22 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> AME DIGITAL AME Digita </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 45.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> AME DIGITAL AME Digita </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 32.98 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> ELO </td>
   <td style="text-align:left;"> 2023-12-24 </td>
   <td style="text-align:left;"> AME DIGITAL AME Digita </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:left;"> NÃO </td>
   <td style="text-align:left;"> Sem Classe </td>
   <td style="text-align:right;"> 9.57 </td>
  </tr>
</tbody>
</table>