install.packages("kableExtra")
library("financetools")
df1 <- ler_conta_BB("data-raw/bb_janeiro.csv")
df2 <- ler_conta_bradesco("data-raw/bradesco_janeiro.xls")
df3 <- ler_fatura_bradesco("data-raw/cartao_janeiro.xls")
df4 <- consolidar_despesas(df1, df2, df3)
library(ggplot2)
grafico_pizza_centro(df4)
writexl::wdata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWElEQVR42mNgGPTAxsZmJsVqQApgmGw1yApwKcQiT7phRBuCzzCSDSHGMKINIeDNmWQlA2IigKJwIssQkHdINgxfmBBtGDEBS3KCxBc7pMQgMYE5c/AXPwAwSX4lV3pTWwAAAABJRU5ErkJggg==rite_xlsx(df4, "tests/despesasjaneiro.xlsx")
